import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const serviceSource = readFileSync("src/server/bot-settings.ts", "utf8");
const routerSource = readFileSync("src/server/api/routers/bot-settings.ts", "utf8");
const panelSource = readFileSync("src/components/app/bot-management-panel.tsx", "utf8");
const shellSource = readFileSync("src/components/app/shell.tsx", "utf8");

assert.match(serviceSource, /sendQqBotTestAnalysis/, "Bot settings service should implement test analysis sending");
assert.match(serviceSource, /testQqBotWsConnection/, "Bot settings service should implement WebSocket connection testing");
assert.match(serviceSource, /startQqBotWsListener/, "Bot settings service should implement a persistent WebSocket listener");
assert.match(serviceSource, /stopQqBotWsListener/, "Bot settings service should support stopping the persistent WebSocket listener");
assert.match(serviceSource, /getQqBotWsLogs/, "Bot settings service should expose recent persistent WebSocket logs");
assert.match(serviceSource, /qqBotRuntimes/, "Bot settings service should keep per-connection listener runtime state");
assert.match(serviceSource, /getQqBotGroups/, "Bot settings service should expose QQ group list from NapLink");
assert.match(serviceSource, /sendQqBotGroupMessage/, "Bot settings service should wrap group message sending for future business actions");
assert.match(serviceSource, /sendQqBotPrivateMessage/, "Bot settings service should wrap private message sending for future business actions");
assert.match(serviceSource, /sendQqBotManualMessage/, "Bot settings service should implement direct manual message sending");
assert.match(serviceSource, /buildEnabledGroupRatesMessage/, "Bot settings service should build a live enabled-group rate message");
assert.match(serviceSource, /\.listGroups\(\)/, "Test analysis should read current target groups in real time");
assert.match(serviceSource, /@naplink\/naplink/, "Test analysis should use the published NapLink package");
assert.match(serviceSource, /new NapLink/, "Test analysis should create a NapLink client");
assert.match(serviceSource, /process\.env\.WS_NO_BUFFER_UTIL/, "NapLink loading should disable ws bufferutil optional native path");
assert.match(serviceSource, /await import\("@naplink\/naplink"\)/, "NapLink should be dynamically imported after ws optional native flags are set");
assert.doesNotMatch(serviceSource, /^import \{ NapLink \} from "@naplink\/naplink";/m, "NapLink should not be statically imported before ws optional native flags are set");
assert.match(serviceSource, /\.sendGroupMessage\(/, "Test analysis should send through NapLink sendGroupMessage");
assert.match(serviceSource, /\.sendPrivateMessage\(/, "Bot settings should send through NapLink sendPrivateMessage");
assert.match(serviceSource, /\.getGroupList\(\)/, "Bot settings should load QQ groups through NapLink getGroupList");
assert.match(serviceSource, /\.getLoginInfo\(\)/, "Bot settings should load current bot QQ through NapLink getLoginInfo");
assert.match(serviceSource, /botUserId/, "Bot settings should persist the current bot QQ number");
assert.match(serviceSource, /botNickname/, "Bot settings should persist the current bot nickname");
assert.match(serviceSource, /\.getStatus\(/, "WebSocket testing should use NapLink getStatus");
assert.match(serviceSource, /\.getState\(\)/, "Persistent listener should expose NapLink connection state");
assert.match(serviceSource, /\.isConnected\(\)/, "Persistent listener should expose NapLink connection connectivity");
assert.match(serviceSource, /diagnoseQqBotWsEndpoint/, "WebSocket testing should run endpoint diagnostics before NapLink connect");
assert.match(serviceSource, /TCP 端口/, "WebSocket diagnostics should report TCP port reachability");
assert.match(serviceSource, /WebSocket 握手/, "WebSocket diagnostics should report WebSocket handshake results");
assert.match(serviceSource, /WebSocket 请求路径/, "WebSocket diagnostics should report the request path without leaking secrets");
assert.match(serviceSource, /Token 已配置/, "WebSocket diagnostics should reveal whether a NapCat token is configured");
assert.match(serviceSource, /响应摘要/, "WebSocket diagnostics should include a safe response summary for handshake failures");
assert.match(serviceSource, /WebSocket 握手预检未通过，继续交由 NapLink 实际连接验证/, "WebSocket handshake precheck should not block the real NapLink connection");
assert.doesNotMatch(serviceSource, /if \(!handshake\.ok\)[\s\S]{0,120}return handshake/, "WebSocket handshake diagnostics should not return early before NapLink tries to connect");
assert.match(serviceSource, /catch \(error\)/, "WebSocket testing should catch expected NapLink connection errors");
assert.match(serviceSource, /ok: false/, "WebSocket testing should return a failed result instead of surfacing expected connection failures as tRPC 500 errors");
assert.match(serviceSource, /\.on\("connect"/, "NapLink client should listen for connect events");
assert.match(serviceSource, /\.on\("disconnect"/, "NapLink client should listen for disconnect events");
assert.match(serviceSource, /\.on\("reconnecting"/, "NapLink client should listen for reconnecting events");
assert.match(serviceSource, /\.on\("message"/, "NapLink client should listen for all message events");
assert.match(serviceSource, /formatQqBotMessageLog/, "Message logs should be normalized by a shared formatter");
assert.match(serviceSource, /普通群消息/, "Message logs should include the normal group-message category");
assert.match(serviceSource, /好友私聊/, "Message logs should include the friend private-message category");
assert.match(serviceSource, /群临时会话/, "Message logs should include the group temporary private-message category");
assert.match(serviceSource, /messageCategoryLabel\(messageType,\s*subType\)/, "Message logs should derive their category from message_type and sub_type");
assert.match(serviceSource, /\$\{messageType\}\/\$\{subType\}/, "Formatted message logs should preserve message_type/sub_type in the output");
assert.doesNotMatch(serviceSource, /\.on\("message\.group"/, "Bot settings should not attach separate group-message listeners");
assert.doesNotMatch(serviceSource, /\.on\("message\.private"/, "Bot settings should not attach separate private-message listeners");
assert.doesNotMatch(serviceSource, /\.on\("message\.group\.normal"/, "Bot settings should not attach separate normal-group-message listeners");
assert.doesNotMatch(serviceSource, /\.on\("message\.private\.friend"/, "Bot settings should not attach separate friend-private-message listeners");
assert.doesNotMatch(serviceSource, /\.on\("message\.private\.group"/, "Bot settings should not attach separate group-temp-private-message listeners");
assert.doesNotMatch(serviceSource, /from "undici"/, "Bot settings should not hand-roll NapCat WebSocket calls");
assert.match(serviceSource, /targetGroupId/, "Test analysis should send to the configured QQ group id");

assert.match(routerSource, /sendTestAnalysis:\s*protectedProcedure/, "Bot settings router should expose a protected sendTestAnalysis endpoint");
assert.match(routerSource, /testWsConnection:\s*protectedProcedure/, "Bot settings router should expose a protected testWsConnection endpoint");
assert.match(routerSource, /startWsListener:\s*protectedProcedure/, "Bot settings router should expose a protected persistent listener start endpoint");
assert.match(routerSource, /stopWsListener:\s*protectedProcedure/, "Bot settings router should expose a protected persistent listener stop endpoint");
assert.match(routerSource, /wsLogs:\s*protectedProcedure/, "Bot settings router should expose a protected WebSocket logs query endpoint");
assert.match(routerSource, /groups:\s*protectedProcedure/, "Bot settings router should expose QQ group list endpoint");
assert.match(routerSource, /sendManualMessage:\s*protectedProcedure/, "Bot settings router should expose manual message sending endpoint");
assert.match(routerSource, /sendQqBotTestAnalysis/, "Bot settings router should call the send service");
assert.match(routerSource, /testQqBotWsConnection/, "Bot settings router should call the WebSocket test service");
assert.match(routerSource, /startQqBotWsListener/, "Bot settings router should call the persistent listener start service");
assert.match(routerSource, /stopQqBotWsListener/, "Bot settings router should call the persistent listener stop service");
assert.match(routerSource, /getQqBotWsLogs/, "Bot settings router should call the persistent log service");
assert.match(routerSource, /getQqBotGroups/, "Bot settings router should call the QQ group list service");
assert.match(routerSource, /sendQqBotManualMessage/, "Bot settings router should call the manual message service");

assert.match(panelSource, /trpc\.botSettings\.sendTestAnalysis\.useMutation/, "Bot panel should call the send test analysis endpoint");
assert.match(panelSource, /trpc\.botSettings\.testWsConnection\.useMutation/, "Bot panel should call the WebSocket test endpoint");
assert.match(panelSource, /trpc\.botSettings\.wsLogs\.useQuery/, "Bot panel should poll persistent WebSocket logs");
assert.match(panelSource, /refetchInterval:\s*1_500/, "Bot panel should refresh WebSocket logs frequently enough for live feedback");
assert.match(panelSource, /trpc\.botSettings\.startWsListener\.useMutation/, "Bot panel should start the persistent WebSocket listener");
assert.match(panelSource, /trpc\.botSettings\.stopWsListener\.useMutation/, "Bot panel should stop the persistent WebSocket listener");
assert.match(panelSource, /trpc\.botSettings\.groups\.useQuery/, "Bot panel should load QQ groups from NapLink");
assert.doesNotMatch(panelSource, /trpc\.botSettings\.groups\.useQuery[\s\S]{0,180}refetchInterval:\s*15_000/, "Bot panel should not poll QQ groups repeatedly and flood logs");
assert.match(panelSource, /trpc\.botSettings\.sendManualMessage\.useMutation/, "Bot panel should send direct messages through NapLink");
assert.match(panelSource, /Bot QQ/, "Bot panel should show the current bot QQ number for later mention detection");
assert.match(panelSource, /测试 WS/, "Bot panel should expose a WebSocket test button");
assert.match(panelSource, /开始监听/, "Bot panel should expose a compact listener start button");
assert.match(panelSource, /停止监听/, "Bot panel should expose a compact listener stop button");
assert.match(panelSource, /wsLogs/, "Bot panel should render operation logs returned by NapLink actions");
assert.match(panelSource, /result\.ok/, "Bot panel should handle failed WebSocket test results without relying on tRPC 500 errors");
assert.doesNotMatch(panelSource, /发送测试分析[\s\S]{0,80}disabled>\s*<Send/, "Send test button should not be hard-disabled");
assert.match(shellSource, /BotWsAutoStarter/, "Shell should auto-start bot WS when a connection is selected");
assert.doesNotMatch(panelSource, /autoStartAttempted/, "Bot panel should not own the auto-start side effect anymore");
